spring:
  application:
    name: spring-boot-exam-2

  datasource:
    url: jdbc:mariadb://localhost:3307/surl_dev
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    com.ll.spring_boot_exam_2: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  site:
    name: "Maria Site"
